refact(pisma, have error): user.name modify to User.mailid
lint(side-effect, commitlintrc): change header-cases option to warning
  and modify type enum 'refactor' to 'refact'

this commit was not passed unit test as below error log:

(node:6168) UnhandledPromiseRejectionWarning:
Error: Variable '$where' expected
value of type 'UserWhereUniqueInput!' but got: {"mailid":"muhun"}. Reason: 'mail
Field 'mailid' is not defined in the input type 'UserWhereUniqueInput'

because type 'UserWhereUniqueInput' not have(?) {mailid: string}
but i think i was already define 'User.mailid' prop into all modified files.